CREATE TABLE employee (
	employee_id varchar(25) PRIMARY KEY NOT NULL,
	employee_first_name varchar(max) NOT NULL,
	employee_last_name	varchar(max) NOT NULL,
);

CREATE TABLE department (
	department_id int PRIMARY KEY NOT NULL,
	department_name varchar(max) NOT NULL
);

CREATE TABLE form(
	form_id	int PRIMARY KEY NOT NULL,
	form_date	date NOT NULL,
	form_campus	varchar(max) NOT NULL,
	form_status varchar(max) NOT NULL,
	employee_id	varchar(25),
	department_id int,
	FOREIGN KEY(employee_id) REFERENCES "employee" ON UPDATE CASCADE,
	FOREIGN KEY(department_id) REFERENCES "department" ON UPDATE CASCADE
);

CREATE TABLE mile (
	mile_date	date NOT NULL,
	mile_description	text NOT NULL,
	mile_fund	varchar(max) NOT NULL,
	mile_org	varchar(max) NOT NULL,
	mile_account	varchar(max) NOT NULL,
	mile_amount	varchar(max) NOT NULL,
	mile_tax	varchar(max) NOT NULL,
	form_id	int NOT NULL,
	FOREIGN KEY("form_id") REFERENCES "form" ON UPDATE CASCADE
);

CREATE TABLE receipt (
	receipt_id	int PRIMARY KEY  NOT NULL,
	receipt_data binary NOT NULL,
);
CREATE TABLE expenses (
	expense_id int PRIMARY KEY NOT NULL,
	expense_date	date NOT NULL,
	expense_description	text NOT NULL,
	expense_fund	varchar(max) NOT NULL,
	expense_org	varchar(max) NOT NULL,
	expense_account	varchar(max) NOT NULL,
	expense_amount	varchar(max) NOT NULL,
	expense_tax	varchar(max) NOT NULL,
	form_id	int,
	receipt_id	int NOT NULL,
	FOREIGN KEY("form_id") REFERENCES "form" ON UPDATE CASCADE,
	FOREIGN KEY("receipt_id") REFERENCES "receipt" ON UPDATE CASCADE
);

CREATE TABLE approval_list (
	approval_fund	int NOT NULL,
	approval_org	int NOT NULL,
	approval_fund_org	int UNIQUE,
	approval_dept	char UNIQUE,
	approval_budget_mang varchar(max) NOT NULL,
	approval_lead	char UNIQUE,
	approval_add_app	varchar(max),
	approval_add_app2	varchar(max),
	approval_add_app3	varchar(max),
	approval_finac_mang	varchar(max)
);

INSERT INTO department (department_id, department_name) VALUES
(101, 'General Adminstration'),
(102, 'General Administration'),
(201,	'Financial Management'),
(211,	'Admin - Accounting'),
(212,	'General Accounting'),
(213,	'Accounts Payable'),
(214,	'Accounts Receivable'),
(215,	'Payroll'),
(221,	'Admin - Purchasing'),
(222,	'Purchasing'),
(223,	'Bookstore'),
(224,	'Merchandising'),
(231,	'Administration - IT'),
(232,	'Cust. Serv.-Univ'),
(233,	'Cust. Serv-West'),
(235,	'Cust Serv-SE'),
(236,	'Network'),
(237,	'Datawarehouse'),
(238,	'Web/Media'),
(239,	'ERP'),
(241,	'Project Management'),
(242,	'Data Security'),
(251,	'Admin - Physical Plant'),
(255,	'Security'),
(256,	'Transportation'),
(257,	'Risk Assessment'),
(261,	'Admin - Athletics'),
(262,	'Athletics-FAR'),
(263,	'Hockey'),
(264,	'Volleyball-Women'),
(265,	'Basketball-Women'),
(266,	'Basketball-Men'),
(267,	'Soccer-Women'),
(268,	'Soccer-Men'),
(269,	'Golf-Women'),
(270,	'Golf-Men'),
(271,	'Cross Country-Women'),
(272,	'Cross Country-Men'),
(273,	'Lacrosse-Women'),
(274,	'Lacrosse-Men'),
(275,	'Track-Women'),
(276,	'Track-Men'),
(277,	'Softball'),
(278,	'Baseball'),
(279,	'Bowling-Women'),
(280,	'Bowling-Men'),
(281,	'Student Center'),
(282,	'Sports Information'),
(283,	'Intramurals'),
(284,	'Cheer-Women'),
(285,	'Dance-Women'),
(286,	'Tennis-Men'),
(287,	'Tennis-Women'),
(288,	'Rugby-Men'),
(289,	'Hockey-DIII'),
(290,	'Athletic Training'),
(291,	'Rugby-Men DII'),
(292,	'Soccer-Men JV'),
(293,	'Volleyball-Women JV'),
(294,	'Basketball-Women JV'),
(295,	'Basketball-Men JV'),
(296,	'Softball-JV'),
(297,	'Baseball-JV'),
(298,	'Athletic Compliance'),
(299,	'Hockey-Women'),
(302,	'Academic Administration'),
(303,	'Faculty Development'),
(304,	'Experiential Learning'),
(305,	'Program Development'),
(306,	'1st year Experience'),
(307,	'Internship Management'),
(308,	'BPA'),
(309,	'DECA'),
(311,	'Admin-School of Health'),
(312,	'Nursing'),
(313,	'Allied Health'),
(315,	'Health Information Mgmt'),
(316,	'Masters of Public Health'),
(317,	'MSN Nursing'),
(318,	'Occup. Therapy-Masters'),
(319,	'Physical Therapy-Doctorate'),
(321,	'Admin-School of Tech'),
(322,	'Computer Info Systems'),
(323,	'Networking '),
(325,	'International'),
(326,	'MSIA'),
(327,	'SOT Security'),
(328,	'Tech. Mgmt.'),
(331,	'Admin-School of Bus'),
(332,	'Accounting'),
(333,	'Finance'),
(334,	'Management'),
(335,	'Marketing'),
(336,	'Law'),
(337,	'Sneden-MBA'),
(338,	'Human Resources'),
(339,	'Public Safety'),
(341,	'Admin-General Education'),
(342,	'English & Communication'),
(343,	'Math'),
(344,	'Economics'),
(345,	'Science'),
(346,	'Social Science'),
(347,	'Data Analytics'),
(348,	'International-Study Abroad'),
(349,	'Executive MBA'),
(351,	'Urban Education'),
(361,	'Masters- Health Information Mgt'),
(362,	'CMBA'),
(363,	'Sports Management'),
(364,	'Industrial Production Management'),
(365,	'Entrpreneurial Center'),
(371,	'Administration-LINC'),
(372,	'Library'),
(373,	'Tutoring'),
(374,	'Computer Lab'),
(375,	'Testing'),
(381,	'Admin-Registrar'),
(384,	'Transfer Articulation'),
(401,	'Admin-Student Services'),
(405,	'Corporate Services'),
(406,	'Career Services'),
(411,	'Admin-Marketing'),
(415,	'Scholarships'),
(416,	'Marketing-Image Campaign'),
(417,	'Marketing-New Location Cpn'),
(418,	'Marketing-RNL'),
(419,	'Marketing-Helix'),
(421,	'Financial Aid'),
(431,	'Institutional Research'),
(432,	'Business Intelligence'),
(433,	'Culture of Quality'),
(440,	'Marketing-Adult Fall 1 Campaign'),
(441,	'Marketing-Adult Fall 2 Campaign'),
(442,	'Marketing-Adult W1 Campaign'),
(443,	'Marketing-Adult W2 Campaign'),
(444,	'Marketing-Adult Sp/Smr Cpn'),
(445,	'Marketing-High School'),
(446,	'Marketing-Community College'),
(447,	'Marketing-MBA'),
(461,	'Admin-Student Life '),
(462,	'Student Activities'),
(464,	'Residence Life'),
(465,	'Registered Student Organizations'),
(466,	'Volunteer Services'),
(467,	'Dining Services'),
(471,	'Admin-Admissions'),
(472,	'Admissions - High School'),
(473,	'Lead Management'),
(474,	'Admin - Community College'),
(475,	'International Admisssions'),
(476,	'IPEx Admissions'),
(481,	'Admin-Student Affairs'),
(501,	'Administration-HR'),
(521,	'Training'),
(522,	'Diversity'),
(601,	'Admin-Univer Realtions'),
(603,	'University Communications'),
(604,	'Gvt & Community Relations'),
(701,	'Admin-Major Gifts'),
(702,	'Grants'),
(703,	'Development'),
(704,	'Capital Campaign'),
(711,	'Alumni'),
(821,	'MI Humanities Grant-Admin'),
(831,	'Campus Compact Grant-Admin'),
(841,	'Vista Volunteer'),
(843,	'DU History'),
(844,	'DU Archives Display Celebration'),
(845,	'Miscellaneous'),
(846,	'Dow Chemical'),
(847,	'Great Michigan Read'),
(848,	'VITA'),
(849,	'MCC Regenerate'),
(850,	'MCC Presidential'),
(851,	'VITA-Marketing'),
(852,	'CISP237'),
(853,	'Steelcase'),
(854,	'Dept. of Defense'),
(855,	'AUPHA'),
(856,	'MNA'),
(857,	'VBSN'),
(858,	'Meemic'),
(859,	'Hearst Foundation'),
(860,	'Grants-Scholarships'),
(861,	'Dress for success'),
(862,	'CSI Davenport'),
(863,	'American Library Assoc'),
(864,	'Summer Camps'),
(865,	'Herman Miller - COUE'),
(866,	'American Council on Education'),
(867,	'Michigan State Police'),
(868,	'Midland Medical Assisting Lag'),
(869,	'American Cancer Society'),
(871,	'GRAAHI Grant'),
(872,	'NSF NOYCE'),
(873,	'RNPC-Registered Nurses in Primary Care'),
(874,	'Michigan VA'),
(875,	'Michigan Board of Nursing'),
(876,	'NSF SFS'),
(960,	'Rugby-Women'),
(961,	'Camps'),
(962,	'Football'),
(963,	'Soccer- Woman JV'),
(964,	'Pep Band'),
(965,	'Wrestling-Men'),
(966,	'Pom Pon'),
(967,	'Volleyball-Men'),
(968,	'Hockey-Men DII'),
(969,	'Athletic-Transportation'),
(970,	'Sideline Cheer'),
(971,	'Marching Band'),
(972,	'Admin Non-Varsity Sports'),
(973,	'Swimming/Diving-Women'),
(974,	'Water Polo-Men'),
(975,	'Water Polo-Women'),
(976,	'E-sports'),
(977,	'Wrestling-Women'),
(978,	'Swimming/Diving-Men'),
(979,	'Stength Conditioning');